services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: brain
      POSTGRES_PASSWORD: brain
      POSTGRES_DB: brain
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker_compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    platform: linux/amd64
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

volumes:
  db_data:


networks:
  docker_compose:
    driver: bridge
